version: "3.9"
services:
    web:
        # name: dotnet-app
        build: .
        ports:
            - "80:5000"
        depends_on:
            - mysqldb
        environment:
          - DBHOST=mysqldb
    mysqldb:
      # name: mysql-database
      image: mysql:8.0     
      environment:
        - MYSQL_ROOT_PASSWORD=Coucou123!
      volumes:
        - mysql:/var/lib/mysql

volumes:
  mysql:
