version: "3.9"
services:
    web:
        build: .
        ports:
            - "80:5000"
            - "443:5001"
        depends_on:
            - mysqldb
        environment:
          - DB_HOST=mysqldb
          - DB_PASSWORD=${DB_PASSWORD}
    mysqldb:
      image: mysql:8.0     
      environment:
        - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      volumes:
        - mysql:/var/lib/mysql

volumes:
  mysql:
